feat: support cluster resource quota
kubewharf/kubezoo pull request #27
Opened 2022-11-10 09:13 UTC by zoumo

#### What type of PR is this?

Feature: support tenant scope quota limit

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2022-11-10 11:49 UTC, caohe commented on .vscode/launch.json
> +
Do we need this vscode config file?

2022-11-15 06:22 UTC, lcw2 commented
can tanant access the API clusterresourcesquota？ 
I think tanant can access the API clusterresourcesquota to know  how much clusterresouces are used.

2022-11-15 06:24 UTC, zoumo commented on .vscode/launch.json
> +
no, I will delete it

2022-11-15 06:29 UTC, zoumo commented
> can tanant access the API clusterresourcesquota？ I think tanant can access the API clusterresourcesquota to know how much clusterresouces are used.

@lcw2 I think no, clusterresourcesquota is a system resource, should not be accessed by tenant by default, maybe we can expose it when system crd feature is ready @Silverglass

2022-11-15 06:37 UTC, lcw2 commented
ok,  when will this  system crd  feature  be release?

2022-11-20 14:39 UTC, Silverglass requested changes

2022-11-20 14:39 UTC, Silverglass commented on cmd/clusterresourcequota/install.go
> +	quota "github.com/kubewharf/kubezoo/pkg/apis/quota"
import style

2022-11-20 14:39 UTC, Silverglass commented on docs/manually-setup-cn.md
> +Export kubezoo server to 6443
中文文档

2022-11-20 14:39 UTC, Silverglass commented on hack/lib/gen_pki.sh
> +readonly TEMP_DIR=$(pwd -P)/_output/pki
用 $REPO_ROOT 比用 $(pwd -P) 更确定点？

2022-11-20 14:39 UTC, Silverglass commented on hack/lib/gen_pki.sh
> +gen_kubezoo_quota_pki() {
这个函数没用到？

2022-11-20 14:39 UTC, Silverglass commented on pkg/clusterresourcequota/controllers/util.go
> +// Copyright 2022 jim.zoumo@gmail.com
Copyright 2022 The KubeZoo Authors.

2022-11-22 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubewharf/kubezoo?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubewharf/kubezoo?pullRequest=27) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubewharf/kubezoo?pullRequest=27) it.</sub>

2022-11-22 10:57 UTC, zoumo commented on docs/manually-setup-cn.md
> +Export kubezoo server to 6443
There is no problem here, this is the output of the script

2022-11-29 10:33 UTC, Silverglass commented on docs/manually-setup.md
>  ```
下面创建 pod 时，需要指定 cpu 和 memory, 以便 resource quota  做认证；中文文档同理

2022-11-29 13:09 UTC, Silverglass commented on cmd/kubezoo/app/server.go
> +		klog.Warningf("failed to init cluster quota client with discovery error %v", err)
也可能是 upstream 不存在这个 group, 所以这里应该判断下错误，而不是直接返回 error ?

2022-12-06 06:27 UTC, Silverglass approved these changes
Thank you very much for your contribution to tenant quota!

2022-12-06 06:27 UTC, merged